language: go
go:
  - "1.16.x"
before_install:
  - go install github.com/mattn/goveralls@latest
  - go install honnef.co/go/tools/cmd/staticcheck@latest
script:
  - staticcheck ./...
  - go test -race ./...
  - goveralls -service=travis-ci
  # $GOPATH/bin/goveralls -service=travis-ci

