language: go

sudo: false

install: true

matrix:
  include:
    - go: "1.10"
    - go: master
      env: COVER=no

  allow_failures:
    - go: master
  fast_finish: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -u gopkg.in/alecthomas/gometalinter.v2
  - gometalinter.v2 --install
  - go get github.com/mattn/goveralls

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go vet ./...
  - gometalinter.v2 --skip=internal --vendor ./...
  - go test -v -race ./...
  # do not report coverage for go tip
  - [ "$COVER" != 'no' ] && go test -v -cover -covermode=count -coverprofile=profile.cov ./...
  - [ "$COVER" != 'no' ] && goveralls -coverprofile=profile.cov -service=travis-ci
