language: go

go: 
 - "1.10"
 - master

sudo: false

install: true

matrix:
  allow_failures:
    - go: master
  # Don't wait for tip tests to finish.
  fast_finish: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  # use golint through gometalinter because it allows to easily ignore the
  # `vendor` and `internal` directories
  - go get -u gopkg.in/alecthomas/gometalinter.v2

script:
  - test -z $(gofmt -s -l $GO_FILES)         # Fail if a .go file hasn't been formatted with gofmt
  - go test -v -race ./...                   # Run all the tests with the race detector enabled
  - go vet ./...
  - gometalinter.v2 --skip=internal --vendor ./...
  # TODO: re-add coverage
