language: go

sudo: false

install: true

matrix:
  include:
   - go: "1.10"
     env: COVER=yes
   - go: master
     env: COVER=no

  allow_failures:
    - go: master
  fast_finish: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -u gopkg.in/alecthomas/gometalinter.v2
  - go get -u github.com/mattn/goveralls
  - gometalinter.v2 --install

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go vet ./...
  - gometalinter.v2 --skip=internal --vendor ./...
  - go test -v -race ./...
  - |
    if [ "$COVER" == "yes" ]; then
      go test -v -cover -covermode=count -coverprofile=profile.cov ./... > /dev/null
      goveralls -coverprofile=profile.cov -service=travis-ci
    fi
